on:
  push:
    branches: [main]
  pull_request:
name: Minimum Supported Rust Version
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.49.0 # parking_lot_core
          override: true
      - uses: actions/checkout@v2
      - name: cargo +1.49.0 check
        uses: actions-rs/cargo@v1
        with:
          command: check
